name: pet_recipe_explorer
description: "A playful showcase of recipes and random animal photos."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # State Management
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  # Networking
  dio: ^5.7.0

  # Data Models & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.4.4

  # Utilities
  equatable: ^2.0.5
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  flutter_gen_runner: ^5.7.0

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter_gen:
  output: lib/core/generated/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/

flutter_intl:
  enabled: true
